Do not persist refresh token payloads
Elfster/openiddict-core pull request #1
Opened 2024-01-26 16:45 UTC by AlbertSchreuder-0

2024-01-29 14:25 UTC, edmacdonald requested changes

2024-01-29 14:25 UTC, edmacdonald commented on src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs
> +                }
This feels wrong to add this here.  Why skip the call to _tokenManager.GetPayloadAsync(token) since that is exactly what you want here?  The TokenManager seems like a better place to decide whether or not to persist the payload.

2024-01-30 19:16 UTC, AlbertSchreuder-0 commented on src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs
> +                }
I've moved the logic regarding the persistence of the token.
I am generating a basic identity given the metadata I have, and then I'm generating a token payload from that. and the rest of the process continues.

2024-01-31 14:43 UTC, edmacdonald commented on src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs
> +                        };
I don't see this code anywhere in the existing solution, so I'm not sure why we need to introduce it.  The issue we are trying to avoid is storing the payload which means that code must already exist to create the payload.  Whereever that is, it needs to be leveraged.

2024-02-08 21:51 UTC, closed without merging